name: Test

on: [pull_request]

jobs:
  npm-package-test:
    name: npm-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
        working-directory: npm-package
      - name: Run Tests
        run: npm run test
        working-directory: npm-package
      - name: Fail on test errors
        if: ${{ failure() }}
        run: exit 1;

path: .github/workflows/npm-package/test.yml
