name: Chrome Extension

on: [pull_request]

jobs:
  chrome-extension-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
        working-directory: chrome-extension
      - name: Run Tests
        run: npm run test
        working-directory: chrome-extension
      - name: Fail on test errors
        if: ${{ failure() }}
        run: exit 1;
