name: Chrome Extension

on: [pull_request]

jobs:
  chrome-extension-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
        working-directory: chrome-extension
      - name: Build
        run: npm run compile
        working-directory: chrome-extension
      - name: Check build status
        run: |
          if [ -f "chrome-extension/build/public/app.bundle.js" ]; then
            echo "Build succeeded!"
          else
            echo "Build failed!"
            exit 1
          fi
