name: NPM Package

on: [pull_request]

jobs:
  npm-package-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
        working-directory: npm-package
      - name: Build
        run: npm run build
        working-directory: npm-package
      - name: Check build status
        run: |
          if test -f "npm-package/build/bundle.d.ts" && \
             test -f "npm-package/build/bundle.js" && \
             test -f "npm-package/build/bundle.js.LICENSE.txt" && \
             test -f "npm-package/build/bundle.js.map"; then
            echo "Build succeeded!"
          else
            echo "Build failed!"
            exit 1
          fi
